### ISSUE TITLE
[Question]: How close is this to being finished?

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [Mrbysco/ForceCraft#25]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

I was wonder how complete the features are for this mod and how close it is to [DartCraft](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1287878-dartcraft-beta-0-2-20)?  Also, will you be taking any features from [FullThrouttle Alchemist](https://www.curseforge.com/minecraft/mc-mods/fullthrottle-alchemist)?

**Comment by Darkosto** [comment]
This mod is intended to be a reverse engineering of Dartcraft. Not every feature can or will be added, but it's designed to be fairly close. I view FullThrottle Alchemist to be an extremely different mod and outside of the scope of this project. What features were you specifically looking for?

**Comment by NorgerLegacy** [comment]
When right-clicked the Baconator will attempt to take Bacon from the user's inventory and store it in its internal storage. Shift-right-clicking will do just the opposite: give Bacon back to the player.
- When the Baconator has Bacon stored and is on the player's hotbar, it will automatically feed the player Bacon when they become hungry enough to eat a piece of Bacon. This expends Bacon from the Baconator's internal storage.
- The Baconator can also function from inside a Force Belt on the player's hotbar.

i see the texture exists for a full baconator but with it and bacon in my inventory (could be mod conflict but i never see it full. 
also will a custom force battery or  integration with another power mod like mekanism come around to charge the force armor and possible limited flight. also any other enchants for the armor to toughen them up?  Also if that will be re-implemented back in will it too have a default texture and a charged texture?

in that dartcraft link they posted is the original dartcraft things is there or will there be a list you could give a basic rundown as to what we can look forward to seeing to come back? like the other armors/tools/weapons

loved this back in the day and mostly just tinker around with making my own resource pack and add various textures so knowing what to come or expect lets me tinker some more.

thank you for bringing this mod back to life in 1.16.5

**Comment by Darkosto** [comment]
Hello @NorgerLegacy 

To follow up on your reply: 



> When right-clicked the Baconator will attempt to take Bacon from the user's inventory and store it in its internal storage. Shift-right-clicking will do just the opposite: give Bacon back to the player.

> * When the Baconator has Bacon stored and is on the player's hotbar, it will automatically feed the player Bacon when they become hungry enough to eat a piece of Bacon. This expends Bacon from the Baconator's internal storage.

This functionality exists, when you shift-click the baconator it will glow indicating auto-feed has been enabled. We'll consider an alternative keybind to remove bacon from the baconator. 





> i see the texture exists for a full baconator but with it and bacon in my inventory (could be mod conflict but i never see it full.

This is a bug and will be fixed




> also will a custom force battery or integration with another power mod like mekanism come around to charge the force armor and possible limited flight. also any other enchants for the armor to toughen them up? Also if that will be re-implemented back in will it too have a default texture and a charged texture?

The mechanics of the mod that already require power (to power the infuser) should already be compatible with other mod's energy systems. There are no plans to "charge" force items with other mod power systems because this is not empowering armor with energy, it's designed to be a magical property. This is outside of the scope of the mod.

The infusions already available in the mod work well. There are no plans to add more enchants. 



> in that dartcraft link they posted is the original dartcraft things is there or will there be a list you could give a basic rundown as to what we can look forward to seeing to come back? like the other armors/tools/weapons

I refer you to the mod in its public state. If you're looking for a feature list, the mod will be the best resource. 

The list of armor/tools/weapons that Forcecraft offer match what Dartcraft had available. Adding more would be outside of the intent for this project. I'm not sure what you may be referring to or if you're under the impression the original mod had more outside of what Forcecraft already offers.


In the future, I urge you to report bugs and features as separate threads on this issue tracker. It becomes increasingly difficult to follow up with reports when they are all in the same message. The devs for this mod would love to be helpful and creating separate issues for each topic makes their job easier. Thanks for your feedback!

**Comment by NorgerLegacy** [comment]
Darkosto I was basing the additons/enhancement/features off of minecraft 1.6 version of bluedarts dartcraft. as to what it had and what is yet to come. i was more or less just trying to stay intopic to your question as to what features the original poster was looking for. since curse has to comment section and this was a broad spectrum already existing post.

**Comment by Darkosto** [comment]
@NorgerLegacy I understand the intent of your response. Originally, it was posed to the original author of the thread. In reponse to your feedback, I would again urge you to organize your ideas into separate bullet points. You had many ideas in a small paragraph and trying to fully understand what you're saying is not easy.
